INSERT INTO tb_category (name, created_At) values ( 'Books', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Lazer', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Roupas', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Calcados', NOW() );INSERT INTO tb_category (name, created_At) values ( 'Books', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Lazer', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Roupas', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Calcados', NOW() );INSERT INTO tb_category (name, created_At) values ( 'Books', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Lazer', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Roupas', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Calcados', NOW() );INSERT INTO tb_category (name, created_At) values ( 'Books', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Lazer', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Roupas', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Calcados', NOW() );INSERT INTO tb_category (name, created_At) values ( 'Books', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Lazer', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Roupas', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Calcados', NOW() );INSERT INTO tb_category (name, created_At) values ( 'Books', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Lazer', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Roupas', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Calcados', NOW() );INSERT INTO tb_category (name, created_At) values ( 'Books', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Lazer', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Roupas', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Calcados', NOW() );INSERT INTO tb_category (name, created_At) values ( 'Books', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Lazer', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Roupas', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Calcados', NOW() );INSERT INTO tb_category (name, created_At) values ( 'Books', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Lazer', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Roupas', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Calcados', NOW() );INSERT INTO tb_category (name, created_At) values ( 'Books', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Lazer', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Roupas', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Calcados', NOW() );INSERT INTO tb_category (name, created_At) values ( 'Books', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Lazer', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Roupas', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Calcados', NOW() );INSERT INTO tb_category (name, created_At) values ( 'Books', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Lazer', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Roupas', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Calcados', NOW() );INSERT INTO tb_category (name, created_At) values ( 'Books', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Lazer', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Roupas', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Calcados', NOW() );INSERT INTO tb_category (name, created_At) values ( 'Books', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Lazer', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Roupas', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Calcados', NOW() );INSERT INTO tb_category (name, created_At) values ( 'Books', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Lazer', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Roupas', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Calcados', NOW() );INSERT INTO tb_category (name, created_At) values ( 'Books', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Lazer', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Roupas', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Calcados', NOW() );INSERT INTO tb_category (name, created_At) values ( 'Books', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Lazer', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Roupas', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Calcados', NOW() );INSERT INTO tb_category (name, created_At) values ( 'Books', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Lazer', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Roupas', NOW() );
INSERT INTO tb_category (name, created_At) values ( 'Calcados', NOW() );
